---
name: Publish ld57 to Itch.io
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IS_MAIN: ${{ contains(github.ref, 'main') }}
  PROJECT_NAME: ld57
  USER: lunicosm
  WORKING_DIRECTORY: .
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.2
        with:
          working-directory: $WORKING_DIRECTORY
          godot-version: 4.4
          godot-channel: stable

      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: $BUTLER_API_KEY
          user: $USER
          game: $PROJECT_NAME
          channel: html5